title: Ascendio
email: ascendiostudies@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Site para revisão de materias.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ascendiostudies

# Build settings
# theme: minima
plugins:
  - jekyll-feed